### ISSUE TITLE
v1.2.1 will not build with supplied Dockerfile

### ISSUE THREAD

**Issue by yorickdowne** [stars-labs/heco-chain#55]
#### System information

Geth version: v1.2.1
OS & Version: Ubuntu 20.04, docker.io

#### Actual behaviour

Build on `golang:1.16-alpine` as in the Dockerfile fails with these errors:

```
# github.com/ethereum/go-ethereum/crypto/secp256k1
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: crypto/secp256k1/gmp/linux-amd64/lib/libgmp.a(assert.o): in function `__gmp_assert_header':
assert.c:(.text+0x35): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: crypto/secp256k1/gmp/linux-amd64/lib/libgmp.a(assert.o): in function `__gmp_assert_fail':
assert.c:(.text+0x95): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: crypto/secp256k1/gmp/linux-amd64/lib/libgmp.a(assert.o): in function `__gmp_assert_header':
assert.c:(.text+0x59): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: crypto/secp256k1/gmp/linux-amd64/lib/libgmp.a(memory.o): in function `__gmp_default_allocate':
memory.c:(.text+0x3c): undefined reference to `__fprintf_chk'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: crypto/secp256k1/gmp/linux-amd64/lib/libgmp.a(memory.o): in function `__gmp_default_reallocate':
memory.c:(.text+0x8f): undefined reference to `__fprintf_chk'
collect2: error: ld returned 1 exit status
util.go:46: exit status 2
exit status 1
make: *** [Makefile:16: geth] Error 1
```

The build succeeds when changing the Dockerfile to use `golang:1.16-bullseye` instead.
